spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        show_sql: true
        format_sql: true